FROM kalilinux:custom

CMD ["bin/sh", "-c", "echo This is your virtual hacking machine, a basic kalilinux containing all you need to execute the attack.'\n'\
You can start by typing any command you want:\
&& bin/sh"]
